version = 0.1
[default.deploy.parameters]
stack_name = "naming-generator-stack"
resolve_s3 = true
s3_prefix = "naming-generator-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "CIDRBlock=\"0.0.0.0/0\""
image_repositories = []
